version: '3'
volumes:
   data:
services:
  database:
    image: postgres:11.3
    environment:
      - POSTGRES_DB=urlshortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.spring
    image: url-shortener-service:1.1
    restart: on-failure
    ports:
      - 8080:8080
  angular-view:
    image: url-shortener-view:1.1
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile.angular
    ports:
      - 4200:4200

